# application.yml
spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB # 파일 업로드 최대 크기
      max-request-size: 50MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  freemarker:
    cache: false

  data:
    redis:
      host: 127.0.0.1
#      host: localhost
      port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
  org.springframework.web.socket: debug
  com.coconut.ubo.config: debug
  com.coconut.ubo.web.controller: debug

server:
  port: 8080


---
spring:
  profiles:
    active: prod # 운영 환경

---

spring:
  profiles:
    active: local # 로컬 환경