spring:
  thymeleaf:
    cache: false # 개발 중에는 캐시를 비활성화하는 것이 좋습니다.
    enabled: true

  datasource:
    url: ${DB_URL}
    #    url: jdbc:mysql://localhost:3306/ubo?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB # 파일 업로드 최대 크기
      max-request-size: 50MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  profiles:
    active: aws

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  freemarker:
    cache: false

  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    s3:
      bucket: sheepawsbucket # 버킷명
    region:
      static: ap-northeast-2 # 버킷 리전
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
  org.springframework.web.socket: debug
  com.coconut.ubo.config: debug
  com.coconut.ubo.web.controller: debug

server:
  port: 8080