# 운영 환경
spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${/ubo/mysql/url}
    username: ${/ubo/mysql/username}
    password: ${/ubo/mysql/password}

cloud:
  aws:
    s3:
      bucket: sheepawsbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
      paramstore:
        enabled: true
    credentials:
      access-key: ${/ubo/aws/access-key}
      secret-key: ${/ubo/aws/secret-key}
